spring.application.name=Bank-Transactions

spring.datasource.username= testBank
spring.datasource.password= testBankPass

spring.h2.console.enabled=true
spring.jpa.show-sql=true

app.bank.account.length = 12

spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=none

