
CREATE SEQUENCE hibernate_sequence START WITH 10 INCREMENT BY 1;

drop table if exists TRANSACTION_HISTORY;
drop table if exists ACCOUNT;
drop table if exists CUSTOMERS;
drop table if exists EMPLOYEE;
drop table if exists BRANCH_DETAILS;


CREATE TABLE IF NOT EXISTS BRANCH_DETAILS (
    BRANCH_ID INT AUTO_INCREMENT PRIMARY KEY,
    BRANCH_CODE VARCHAR(10) UNIQUE NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    IFSC_CODE VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
	EMPLOYEE_ID  INT AUTO_INCREMENT PRIMARY KEY,
	EMPLOYEE_NAME VARCHAR(50) UNIQUE NOT NULL,
 	BRANCH_CODE VARCHAR(10) UNIQUE NOT NULL,
    FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH_DETAILS(BRANCH_CODE)

);


CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    ADDRESS TEXT
);
CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    BALANCE DECIMAL(15, 2) NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    CREATED_BY INT ,
    BRANCH_CODE VARCHAR(10)  NOT NULL,
    FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH_DETAILS(BRANCH_CODE) ON DELETE CASCADE ,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTION_HISTORY (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    TRANSACTION_TYPE VARCHAR(10) NOT NULL CHECK (TRANSACTION_TYPE IN ('DEBIT', 'CREDIT')),  
    DESCRIPTION TEXT,
    ACCOUNT_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    BALANCE_AFTER_TRANSACTION DECIMAL(15, 2) NOT NULL,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE
);


